/**
 * Phase 5 — Audit log types.
 *
 * Append-only collection of structured events. Every state change of
 * interest in the system writes one row: webhook ingress, identity
 * resolution, job lifecycle transitions, computer callbacks, and
 * notification deliveries.
 *
 * The schema is intentionally flat and the union of event kinds is
 * closed at the type level, so new sources can't silently start
 * writing untyped rows. Adding a new kind is a one-line schema change
 * + emitter wiring.
 *
 * Storage shape: documents in `audit_events/`, ordered by `at` (ISO
 * timestamp) and indexed by `uid`. The dashboard reads recent rows;
 * forensic queries hit Firestore directly.
 */

import { z } from 'zod';

/* -------------------------------------------------------------------------- */
/* Event kinds                                                                 */
/* -------------------------------------------------------------------------- */

export const AUDIT_EVENT_KINDS = [
  /** A new identity binding was created or replaced. */
  'identity.bound',
  /** An identity was revoked. */
  'identity.revoked',
  /** Inbound webhook arrived from the gateway. */
  'webhook.inbound.received',
  /** Inbound webhook was rejected (auth, schema, unknown mapping, mismatch). */
  'webhook.inbound.rejected',
  /** Inbound webhook was a replay (deduped against webhook_events). */
  'webhook.inbound.deduped',
  /** A job entered the queue. */
  'job.enqueued',
  /** Job picked up by a worker (claimed). */
  'job.claimed',
  /** Job parked awaiting an external callback (Computer). */
  'job.awaiting',
  /** Job completed successfully. */
  'job.done',
  /** Job failed (terminal — no more retries). */
  'job.failed',
  /** Job re-queued for another attempt. */
  'job.requeued',
  /** Computer callback resumed a parked job. */
  'computer.callback.received',
  /** Computer callback was rejected (status, task-id, schema). */
  'computer.callback.rejected',
  /** Outbound notification delivered to the gateway. */
  'notification.delivered',
  /** Outbound notification dropped (no channel, quiet hours, render error). */
  'notification.dropped',
  /** Outbound notification failed at the gateway (4xx/5xx exhausted). */
  'notification.failed',
] as const;
export type AuditEventKind = (typeof AUDIT_EVENT_KINDS)[number];

/* -------------------------------------------------------------------------- */
/* Schema                                                                      */
/* -------------------------------------------------------------------------- */

export const AuditEventSchema = z.object({
  /** Auto-generated by the audit writer. Used for stable ordering. */
  id: z.string().min(1),
  /** ISO timestamp; the writer always sets this — never trust callers. */
  at: z.string().datetime({ offset: true }),
  /** Event kind — closed enum so emitters can't drift. */
  kind: z.enum(AUDIT_EVENT_KINDS),
  /** Cockpit user this event is on behalf of. 'system' for unattributed events. */
  uid: z.string().min(1),
  /** Source surface that emitted the event. */
  source: z.enum(['webhook', 'engine', 'queue', 'fabric', 'computer', 'identity']),
  /** Stable correlator: jobId for job events, eventId for webhooks, notificationId for notifies. */
  ref: z.string().min(1).nullable().default(null),
  /** Free-form structured detail. Stays JSON for forward-compat. */
  data: z.record(z.string(), z.unknown()).default({}),
});
export type AuditEvent = z.infer<typeof AuditEventSchema>;

/** Input shape — the writer fills in id and at. */
export const AuditEmitInputSchema = z.object({
  kind: z.enum(AUDIT_EVENT_KINDS),
  uid: z.string().min(1),
  source: AuditEventSchema.shape.source,
  ref: z.string().min(1).optional(),
  data: z.record(z.string(), z.unknown()).optional(),
});
export type AuditEmitInput = z.infer<typeof AuditEmitInputSchema>;

/* -------------------------------------------------------------------------- */
/* Query types                                                                 */
/* -------------------------------------------------------------------------- */

export interface AuditQuery {
  /** Filter by uid. */
  uid?: string;
  /** Filter by event kind. */
  kind?: AuditEventKind;
  /** Filter by source. */
  source?: AuditEvent['source'];
  /** Inclusive ISO lower bound. */
  since?: string;
  /** Inclusive ISO upper bound. */
  until?: string;
  /** Maximum rows; default 100. */
  limit?: number;
}
